# Created by jmclaren7
version: '3.9'

services:
    fortigate-script:
        image: mcr.microsoft.com/powershell
        volumes:
            - ./data:/data
        restart: always
        environment:
            TZ: America/New_York
        env_file:
            - ./.env
        entrypoint: /usr/bin/pwsh -File /data/fgbackup.ps1
